config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, :restaurant_id, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new(restaurant_params)
  end

  def create
  end

  private

  def restaurant_params
    params.require(:restaurants).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<div class='row'>
<% @restaurants.each do |r| %>
  <div class="card m-3" style="width: 18rem;">
    <img class="card-img-top" src="https://source.unsplash.com/random/?restaurant" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%= r.name %></h5>
      <p class="card-text"><%= r.address %> | <%= r.phone_number %> | <%= r.category %></p>
      <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
      <%= link_to 'See more >', restaurant_path(r.id), class: 'btn btn-primary'  %>
    </div>
  </div>
<% end %>
</div>
  <%# <% raise %> %>

app/views/restaurants/show.html.erb
 <div class="card col m-3" style="width: 100vh; height: 100vh">
    <img class="card-img-top" src="https://source.unsplash.com/random/?restaurant" alt="Card image cap" style="height: 50%">
    <div class="card-body">
      <h5 class="card-title"><%= @restaurant.name %></h5>
      <p class="card-text"><%= @restaurant.address %><%= @restaurant.phone_number %><%= @restaurant.category %></p>
      <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
      <%= link_to 'Go back', restaurants_path, class: 'btn btn-primary'  %>
    </div>
  </div>